services:
  denoise_vid:
    image: denoise_vid_img
    build:
      context: .
      dockerfile: Dockerfile
    container_name: denoise_vid
    working_dir: /home/ws
    volumes:
      - ~/Documents/test:/home/amtc_ws/test
    stdin_open: true
    tty: true
    gpus: all
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
