services:
  comp_int_container:
    image: comp_int
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comp_int_container
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/Documents/EL4106:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
 
