services:
  jax_brax_mjx:
    image: jax_brax_mjx:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jax_brax_mjx
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ~/Documents/amtc_internship:/home/amtc_ws/test
      - ~/Documents/Holistic-Robot-Pose-Estimation:/home/amtc_ws/Holistic-Robot-Pose-Estimation
    working_dir: /home/amtc_ws
    stdin_open: true
    tty: true
    gpus: all
