FROM osrf/ros:noetic-desktop-full

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
    ros-noetic-turtlebot3-gazebo \
    ros-noetic-turtlebot3-teleop \
    ros-noetic-slam-gmapping \
    ros-noetic-map-server \
    git \
    curl \
    vim \
    vim-gtk3 \
    nano

WORKDIR /home
RUN git clone https://github.com/Felipeipe/el5206_ws.git
WORKDIR /home/el5206_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /home/el5206_ws/devel/setup.bash" >> ~/.bashrc
RUN echo "alias c='clear'" >> ~/.bashrc
RUN echo "export TURTLEBOT3_MODEL=burger" >> ~/.bashrc
